// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALuMEq7jMEbNw7lxjDJF2wn6_Mf0OjAzc',
    appId: '1:1022580257222:web:859ff0671a073315e782c7',
    messagingSenderId: '1022580257222',
    projectId: 'vize030119010',
    authDomain: 'vize030119010.firebaseapp.com',
    storageBucket: 'vize030119010.appspot.com',
    measurementId: 'G-XC4BXRNTNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbfI8RUWAPuPOmzi0Z-3mAPSp_PAsL-cI',
    appId: '1:1022580257222:android:e0a0186120e7ff20e782c7',
    messagingSenderId: '1022580257222',
    projectId: 'vize030119010',
    storageBucket: 'vize030119010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzmTRyIFEH0E5pmVkgWLN-Vunyxr0Uw0c',
    appId: '1:1022580257222:ios:4d053f9b59d57e0ee782c7',
    messagingSenderId: '1022580257222',
    projectId: 'vize030119010',
    storageBucket: 'vize030119010.appspot.com',
    iosClientId: '1022580257222-nv36dk1r276jp4seesjbmpljfi0085km.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzmTRyIFEH0E5pmVkgWLN-Vunyxr0Uw0c',
    appId: '1:1022580257222:ios:4d053f9b59d57e0ee782c7',
    messagingSenderId: '1022580257222',
    projectId: 'vize030119010',
    storageBucket: 'vize030119010.appspot.com',
    iosClientId: '1022580257222-nv36dk1r276jp4seesjbmpljfi0085km.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
